"""
search_manager.py

Coordinates execution of all search tasks.

The SearchManager receives search tasks generated by the
SourceSelector and delegates them to the appropriate
search providers.
"""

from models.schemas import SearchTask
from utils.logger import logger


class SearchManager:
    """
    Coordinates search execution.
    """

    def prepare_execution(
        self,
        tasks: list[SearchTask]
    ) -> list[SearchTask]:

        logger.info(
            f"Preparing {len(tasks)} search task(s)..."
        )

        return tasks