"""
source_selector.py

Determines how the ResearchPlan should be executed.

The LLM decides WHAT categories of information should be searched.
This module decides WHICH search provider(s) should execute those
categories.
"""

from models.schemas import (
    ResearchPlan,
    SearchTask,
)
from utils.logger import logger


class SourceSelector:
    """
    Converts a ResearchPlan into executable search tasks.
    """

    def create_search_tasks(
        self,
        plan: ResearchPlan
    ) -> list[SearchTask]:
        """
        Create executable search tasks from the ResearchPlan.

        Args:
            plan: Research plan generated by the planner.

        Returns:
            List of SearchTask objects.
        """

        logger.info("Creating search tasks...")

        tasks: list[SearchTask] = []

        for source in plan.preferred_sources:

            tasks.append(
                SearchTask(
                    provider="tavily",
                    category=source,
                    max_results=plan.max_results,
                )
            )

        logger.info(f"Created {len(tasks)} search tasks.")

        return tasks