"""
formatter.py

Formats the structured ResearchReport into a clean Markdown report.

Design Decision
---------------
The LLM is responsible only for generating structured information.

This formatter is responsible only for presentation.

By generating Markdown, the same output can be reused by:

• Streamlit
• Markdown Export
• PDF Export

without additional formatting logic.
"""

from models.schemas import ResearchReport


class ReportFormatter:

    def format(
        self,
        report: ResearchReport
    ) -> str:

        lines = []

        # --------------------------------------------------
        # Title
        # --------------------------------------------------

        lines.append("# 🤖 Autonomous Research Report")
        lines.append("")

        # --------------------------------------------------
        # Executive Summary
        # --------------------------------------------------

        lines.append("## 📌 Executive Summary")
        lines.append("")
        lines.append(report.executive_summary.strip())
        lines.append("")

        # --------------------------------------------------
        # Key Points
        # --------------------------------------------------

        lines.append("## 🔑 Key Points")
        lines.append("")

        for point in report.key_points:
            lines.append(f"- {point}")

        lines.append("")

        # --------------------------------------------------
        # Important Findings
        # --------------------------------------------------

        lines.append("## 📊 Important Findings")
        lines.append("")

        for finding in report.important_findings:
            lines.append(f"- {finding}")

        lines.append("")

        # --------------------------------------------------
        # References
        # --------------------------------------------------

        lines.append("## 📚 References")
        lines.append("")

        for index, reference in enumerate(report.references, start=1):
            lines.append(f"{index}. {reference}")

        lines.append("")

        # --------------------------------------------------
        # Actionable Insights
        # --------------------------------------------------

        lines.append("## ✅ Actionable Insights")
        lines.append("")

        for insight in report.actionable_insights:
            lines.append(f"- {insight}")

        lines.append("")

        # --------------------------------------------------
        # Limitations
        # --------------------------------------------------

        lines.append("## ⚠️ Limitations")
        lines.append("")

        for limitation in report.limitations:
            lines.append(f"- {limitation}")

        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("*Generated by the Autonomous Research Agent*")

        return "\n".join(lines)