"""
schemas.py

Shared data models used across the Autonomous Research Agent.

These schemas define the standard data structures exchanged between
different modules of the application. Keeping all shared models in one
place ensures consistency, easier debugging, and strong type validation.
"""

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field


class UserQuery(BaseModel):
    """
    Represents a user's research request.
    """

    query: str = Field(..., description="Research topic entered by the user") # Filed -> adds validation and metadata.
    max_results: int = Field(default=5, ge=1, le=20) 
    export_pdf: bool = False
    export_markdown: bool = True
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class ResearchPlan(BaseModel):
    """
    Output generated by the Planner module.
    """

    topic: str = Field(description="Main research topic")
    intent: str = Field(description="User's research intent")
    keywords: List[str] = Field(
        description="Search keywords"
    )
    preferred_sources: List[str] = Field(
        description="Best categories of information sources"
    )
    search_strategy: str = Field(
        description="Recommended search strategy"
    )
    time_sensitive: bool = Field(
        description="Whether recent information is required"
    )
    max_results: int = Field(
        default=5,
        description="Maximum number of search results"
    )
class SearchTask(BaseModel):
    """
    Represents a search task generated from the research plan.
    """

    provider: str = Field(
        description="Search provider that should execute the task"
    )

    category: str = Field(
        description="Category of information to search"
    )

    max_results: int = Field(
        default=5,
        description="Maximum number of results"
    )


class SearchResult(BaseModel):
    """ Represents a single search result returned by a search engine."""
   

    title: str
    url: str
    snippet: str
    source: str
    relevance_score: Optional[float] = None


class SourceDocument(BaseModel):
    """
    Represents the extracted content of a webpage or document.
    """

    title: str
    url: str
    content: str
    source: str
    author: Optional[str] = None
    published_date: Optional[str] = None


class SourceReference(BaseModel):
    """
    Represents a reference included in the final report.
    """

    title: str
    url: str
    source: str
    retrieved_at: datetime = Field(default_factory=datetime.utcnow)


class ResearchReport(BaseModel):
    """
    Final structured report generated by the AI agent.
    """

    query: str
    executive_summary: str

    key_points: List[str]

    important_findings: List[str]

    actionable_insights: List[str]

    references: List[SourceReference]

    generated_at: datetime = Field(default_factory=datetime.utcnow)