"""
schemas.py

Shared data models used across the Autonomous Research Agent.

These schemas define the standard data structures exchanged between
different modules of the application. Keeping all shared models in one
place ensures consistency, easier debugging, and strong type validation.
"""

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field


class UserQuery(BaseModel):
    """
    Represents a user's research request.
    """

    query: str = Field(..., description="Research topic entered by the user") # Filed -> adds validation and metadata.
    max_results: int = Field(default=5, ge=1, le=20) 
    export_pdf: bool = False
    export_markdown: bool = True
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class ResearchPlan(BaseModel):
    """
    Output generated by the Planner module.
    """

    topic: str = Field(description="Main research topic")
    intent: str = Field(description="User's research intent")
    keywords: List[str] = Field(
        description="Search keywords"
    )
    preferred_sources: List[str] = Field(
        description="Best categories of information sources"
    )
    search_strategy: str = Field(
        description="Recommended search strategy"
    )
    time_sensitive: bool = Field(
        description="Whether recent information is required"
    )
    max_results: int = Field(
        default=5,
        description="Maximum number of search results"
    )

class SearchTask(BaseModel):
    """
    Represents one executable search task.
    """

    provider: str = Field(
        description="Search provider"
    )

    query: str = Field(
        description="Actual search query"
    )

    category: str = Field(
        description="Source category"
    )

    max_results: int = Field(
        default=5,
        description="Maximum search results"
    )


class SearchResult(BaseModel):
    """ Represents a single search result returned by a search engine."""
   

    title: str
    url: str
    snippet: str
    source: str
    relevance_score: Optional[float] = None


class SourceDocument(BaseModel):
    """
    Represents the extracted content of a webpage or document.
    """

    title: str = Field(
        description="Title of the document"
    )
    url: str = Field(
        description="Original source URL"
    )
    snippet: str = Field(
        description="Short preview text from the search result"
    )
    content: str = Field(
        description="Full extracted text content"
    )
    source: str = Field(
        description="Source provider (e.g. Tavily)"
    )
    author: Optional[str] = Field(
        default=None,
        description="Author of the document if available"
    )

    published_date: Optional[str] = Field(
        default=None,
        description="Publication date if available"
    )

class SourceReference(BaseModel):
    """
    Represents a reference included in the final report.
    """

    title: str
    url: str
    source: str
    retrieved_at: datetime = Field(default_factory=datetime.utcnow)

class ResearchReport(BaseModel):
    """
    Final structured research report generated by the AI agent.

    Design Decision
    ---------------
    Instead of generating unstructured text, the LLM returns a validated
    structured object.

    Benefits:
    - Easy PDF generation
    - Easy Markdown export
    - Easy Streamlit rendering
    - Strong validation
    - Cleaner architecture
    """

    executive_summary: str = Field(
        description="Overall summary of the research topic."
    )

    key_points: list[str] = Field(
        description="Important key points."
    )

    important_findings: list[str] = Field(
        description="Major findings discovered during research."
    )

    references: list[str] = Field(
        description="Reference URLs or source names."
    )

    actionable_insights: list[str] = Field(
        description="Actionable recommendations."
    )

    limitations: list[str] = Field(
        description="Known limitations or assumptions."
    )